//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by xpln_obj_io.rc
//
#define NO_IDS                          0
#define ROLL_LODOBJ                     104
#define ROLL_MAINOBJ_ATTR               105
#define IDD_ROLL_BASEATTR_OBJ           106
#define ROLL_MANIP_MAIN                 107
#define ROLL_MANIP_DRAGXY               108
#define ROLL_MANIP_DRAGXYZ              109
#define ROLL_MANIP_COMMAND              110
#define ROLL_MANIP_COMMAND_AXIS         111
#define ROLL_MANIP_PUSH                 112
#define ROLL_MANIP_RADIO                113
#define ROLL_MANIP_TOGGLE               114
#define ROLL_MANIP_DELTA                115
#define ROLL_MANIP_WRAP                 116
#define IDD_DOCK                        117
#define ROLL_MANIP_DRAGXYZ_PIX          118
#define IDD_ROLL_LIGHT_MAIN_OBJ         119
#define IDD_ROLL_LIGHT_NAMED_OBJ        120
#define IDD_ROLL_LIGHT_SPILLCUST_OBJ    121
#define IDD_ROLL_LIGHT_PARAM_OBJ        122
#define IDD_ROLL_LIGHT_CUST_OBJ         123
#define IDD_ROLL_ANIM_OBJ               124
#define IDD_TOOL_CALC_ANIM_VALUE        125
#define ROLL_LODOBJ_DISPLAY             127
#define DLG_EXPORT                      128
#define DLG_ABOUT                       131
#define IDS_ROLL_LOD                    133
#define IDS_NEAR                        134
#define ROLL_MAINOBJ_GLOB_SHADING       134
#define IDS_FAR                         135
#define IDS_ROLL_LOD_DISPLAY            136
#define IDS_SCALE                       137
#define IDS_ROLL_MAINOBJ_ATTR           138
#define ROLL_MAINOBJ_COCKPIT            138
#define IDS_ROLL_MAINOBJ_EXP            139
#define IDS_ROLL_GLOB_SHADING           140
#define IDS_TEXTURE_TYPES               142
#define IDS_NONE                        143
#define DLG_ANIM_VIS                    143
#define IDS_TEXTURE_CAPTION             144
#define IDS_TEXTURE_LIT_CAPTION         145
#define DLG_ANIM                        145
#define IDS_TEXTURE_NORMAL_CAPTION      146
#define IDS_BTN_DELETE                  147
#define IDS_ROLL_GLOB_ATTR              150
#define IDS_ROLL_GLOB_COCKPIT           151
#define IDS_MAIN_MENU_CATEGORY          163
#define IDS_MAIN_MENU_DONATE            164
#define IDS_MAIN_MENU_DOC               165
#define IDS_MAIN_MENU_UPDATE            166
#define IDS_MAIN_MENU_ABOUT             167
#define IDS_MAIN_MENU_ACTION_TABLE_CATEGORY 168
#define IDS_MAIN_MENU_SETTINGS          169
#define IDS_ROLL_SMOKE_ATTR             170
#define IDS_ROLL_SMOKE_DISPLY           171
#define IDS_MAIN_MENU_CPP_MESH          172
#define ROLL_MANIP_WHEEL                200
#define ROLL_MANIP_COMMAND_KNOB         201
#define ROLL_MANIP_AXIS_KNOB            204
#define ROLL_MANIP_NOOP                 206
#define CHK_SCALE_ENABLE                1008
#define CHK_SLUNGLOAD                   1009
#define CHK_LODDRAPED                   1011
#define CHK_TILTED                      1015
#define CHK_SLOPELIMIT                  1016
#define CHK_SHADOW                      1017
#define CHK_NORMAL_METALNESS            1017
#define CHK_BLEND_GLASS                 1018
#define CHK_TREE                        1024
#define CHK_TWO_SIDED                   1025
#define CHK_SOLIDCAMERA                 1026
#define CHK_ENABLE_MESH                 1029
#define CHK_DRAW                        1030
#define CHK_ENABLE_LINE                 1031
#define CHK_ENABLE_LIGHT                1033
#define CHK_ENABLE_ANIM                 1035
#define CHK_NAME_MESH                   1036
#define CHK_NAME_LINE                   1037
#define CHK_NAME_LIGHT                  1038
#define CHK_NAME_DUMMY                  1039
#define CHK_NAME_TREE                   1040
#define IDC_BTN_DATAREF                 1041
#define CHK_ENABLE_OPTIMISATION         1041
#define CMB_LAYERGROUP                  1042
#define CHK_ENABLE_INSTANCING           1042
#define CHK_ENABLE_DEBUG                1043
#define BTN_Y_DATAREF                   1043
#define CMB_LAYERGROUP_DRAPED           1044
#define SPN_SLUNGLOAD_EDIT              1045
#define SPN_SLUNGLOAD                   1046
#define SPN_LAYERGROUP_EDIT             1047
#define SPN_LAYERGROUP                  1048
#define CHK_DRAPED                      1049
#define IDC_EDIT_DATAREF                1053
#define SPN_LIGHTLEVEL_V1_EDIT          1054
#define SPN_LIGHTLEVEL_V1               1055
#define SPN_LIGHTLEVEL_V2_EDIT          1056
#define SPN_LIGHTLEVEL_V2               1057
#define CHK_LIGHTLEVEL                  1058
#define CHK_POLYOFFSET                  1059
#define SPN_POLYOFFSET_DIST_EDIT        1060
#define SPN_POLYOFFSET_DIST             1061
#define CHK_COCKPIT                     1062
#define CHK_HARD                        1063
#define CHK_SHINY                       1064
#define IDC_DOCK_ROLLUPS                1065
#define CHK_HARD_DECK                   1065
#define CMB_MANIPTYPE                   1066
#define EDIT_X_DATAREF                  1084
#define EDIT_Y_DATAREF                  1085
#define BTN_X_DATAREF                   1086
#define IDC_V2_EDIT                     1089
#define IDC_V2_SPIN                     1091
#define SPN_UP_EDIT                     1095
#define SPN_UP                          1096
#define SPN_ON_EDIT                     1099
#define SPN_ON                          1101
#define SPN_OFF_EDIT                    1103
#define SPN_OFF                         1104
#define SPN_DX_EDIT                     1105
#define SPN_DX                          1106
#define SPN_STEP_EDIT                   1107
#define SPN_STEP                        1108
#define SPN_EXP_EDIT                    1109
#define SPN_EXP                         1110
#define IDC_CMB_LIGHTTYPE               1111
#define IDC_A_EDIT                      1112
#define IDC_CMB_LIGHTNAMED              1113
#define IDC_A_SPIN                      1114
#define IDC_SIZE_EDIT                   1115
#define IDC_SIZE_SPIN                   1116
#define IDC_R_EDIT                      1117
#define IDC_R_SPIN                      1118
#define IDC_G_EDIT                      1119
#define IDC_G_SPIN                      1120
#define IDC_B_EDIT                      1121
#define IDC_B_SPIN                      1122
#define IDC_EDIT_PARAMS                 1123
#define IDC_S1_EDIT                     1124
#define IDC_EDIT_NAME                   1124
#define IDC_S1_SPIN                     1125
#define IDC_T1_EDIT                     1126
#define IDC_T1_SPIN                     1127
#define IDC_S2_EDIT                     1128
#define IDC_S2_SPIN                     1129
#define IDC_T2_EDIT                     1130
#define IDC_BTN_CANCEL                  1130
#define IDC_T2_SPIN                     1131
#define IDC_BTN_OK                      1131
#define IDC_SCALE_EDIT                  1132
#define IDC_STATIC_CUST                 1132
#define SPN_FAR_EDIT                    1133
#define IDC_SCALE_SPIN                  1134
#define BTN_DONATE                      1135
#define SPN_FAR                         1135
#define ROLL_MAINOBJ_EXP                1135
#define BTN_CHECK_FOR_UPDATE            1136
#define SPN_LAYERGROUP_DRAPED_EDIT      1136
#define ROLL_SMOKEOBJ_DISPLAY           1136
#define LBL_VERSION                     1137
#define SPN_LAYERGROUP_DRAPED           1137
#define ROLL_SMOKEOBJ_ATTR              1137
#define BTN_CLEAR                       1137
#define USER_OUPUT                      1138
#define SPN_LODDRAPED_DIST_EDIT         1138
#define ROLL_MANIP_PANEL                1138
#define BTN_OK                          1139
#define SPN_LODDRAPED_DIST              1139
#define IDD_UPDATED_OBJECTS             1139
#define BTN_CANCEL                      1140
#define SPN_SLOPELIMIT_ROLLMAX_EDIT     1140
#define BTN_ABOUT                       1141
#define SPN_SLOPELIMIT_ROLLMAX          1141
#define BTN_NEW_DATA                    1141
#define LBL_TEXT                        1142
#define SPN_SLOPELIMIT_PITCHMAX_EDIT    1142
#define BTN_SAVE_LOG                    1142
#define SPN_SLOPELIMIT_PITCHMAX         1143
#define LBL_TEXT2                       1143
#define SPN_NEAR_EDIT                   1144
#define SPN_SLOPELIMIT_ROLLMIN_EDIT     1144
#define SPN_NEAR                        1145
#define SPN_SLOPELIMIT_ROLLMIN          1145
#define CMB_BLEND                       1146
#define SPN_SLOPELIMIT_PITCHMIN_EDIT    1146
#define SPN_SCALE_EDIT                  1147
#define SPN_SLOPELIMIT_PITCHMIN         1147
#define CMB_COCKPIT                     1147
#define SPN_SCALE                       1148
#define CMB_WETDRY                      1148
#define CMB_HARD                        1148
#define IDC_V1_EDIT                     1151
#define SPN_BLEND_EDIT                  1151
#define SPN_SHINY_EDIT                  1152
#define IDC_V1_SPIN                     1153
#define SPN_BLEND                       1153
#define SPN_SHINY                       1154
#define CHK_TINT                        1156
#define CHK_SPECULAR                    1157
#define SPN_MAX_EDIT2                   1157
#define SPN_TINT_EMISS                  1158
#define SPN_TINT_EMISS_EDIT             1159
#define SPN_MAX2                        1159
#define SPN_TINT_ALBEDO_EDIT            1160
#define SPN_TINT_ALBEDO                 1161
#define SPN_MIN_EDIT2                   1161
#define SPN_SPECULAR_EDIT               1162
#define SPN_SPECULAR                    1163
#define SPN_MIN2                        1163
#define BTN_TEXTURE_NORMAL              1164
#define BTN_TEXTURE_LIT                 1165
#define BTN_TEXTURE                     1166
#define EDT_PATH_PREFIX                 1167
#define CHK_COCKPITLIT                  1168
#define CHK_NOSHADOW                    1173
#define CHK_COCKPIT_REGION_1            1174
#define SPN_COCKPIT_1_T_EDIT            1175
#define SPN_COCKPIT_1_T                 1176
#define SPN_COCKPIT_1_R_EDIT            1177
#define SPN_COCKPIT_1_L_EDIT            1178
#define SPN_COCKPIT_1_B_EDIT            1179
#define SPN_COCKPIT_1_R                 1180
#define SPN_COCKPIT_1_B                 1181
#define SPN_COCKPIT_1_L                 1182
#define SPN_COCKPIT_2_R_EDIT            1183
#define EDT_LIGHTLEVEL_DRF              1183
#define SPN_COCKPIT_2_R                 1184
#define BTN_LIGHTLEVEL_DRF              1184
#define CHK_COCKPIT_REGION_2            1185
#define STC_GROUP_NAME                  1185
#define SPN_COCKPIT_2_T_EDIT            1186
#define CHK_ENABLE                      1186
#define SPN_COCKPIT_2_T                 1187
#define SPN_VAL_EDIT                    1187
#define SPN_COCKPIT_2_B_EDIT            1188
#define SPN_VAL                         1188
#define SPN_COCKPIT_2_B                 1189
#define BTN_DATAREF                     1189
#define SPN_COCKPIT_2_L_EDIT            1190
#define EDIT_DATAREF                    1190
#define SPN_COCKPIT_2_L                 1191
#define CHK_REVERSE                     1191
#define SPN_COCKPIT_3_R_EDIT            1192
#define BTN_REVERSE_VALUE               1192
#define SPN_COCKPIT_3_R                 1193
#define BTN_CALC_VALUE                  1193
#define CHK_COCKPIT_REGION_3            1194
#define CHK_LOOP                        1194
#define EDIT_KEY                        1194
#define SPN_COCKPIT_3_T_EDIT            1195
#define SPN_LOOP_EDIT                   1195
#define EDIT_VALUE_TYPE                 1195
#define SPN_COCKPIT_3_T                 1196
#define SPN_LOOP                        1196
#define EDIT_VALUE_UNITS                1196
#define SPN_COCKPIT_3_B_EDIT            1197
#define LIST_VALUES                     1197
#define EDIT_DESCRIPTION                1197
#define SPN_COCKPIT_3_B                 1198
#define SPN_COCKPIT_3_L_EDIT            1199
#define BTN_ADD_SHOW                    1199
#define SPN_COCKPIT_3_L                 1200
#define BTN_ADD_HIDE                    1200
#define SPN_COCKPIT_4_R_EDIT            1201
#define BTN_DELETE                      1201
#define SPN_COCKPIT_4_R                 1202
#define SPN_VISIBILITY_V1_EDIT          1202
#define CHK_COCKPIT_REGION_4            1203
#define SPN_VISIBILITY_V1               1203
#define SPN_COCKPIT_4_T_EDIT            1204
#define SPN_VISIBILITY_V2_EDIT          1204
#define SPN_COCKPIT_4_T                 1205
#define SPN_VISIBILITY_V2               1205
#define SPN_COCKPIT_4_B_EDIT            1206
#define BTN_TEXTURE_DEL                 1206
#define SPN_COCKPIT_4_B                 1207
#define BTN_TEXTURE_LIT_DEL             1207
#define SPN_DELTA_EDIT                  1207
#define SPN_COCKPIT_4_L_EDIT            1208
#define BTN_TEXTURE_NORMAL_DEL          1208
#define SPN_DELTA                       1208
#define SPN_COCKPIT_4_L                 1209
#define SPN_CLICK_DELTA_EDIT            1209
#define SPN_CLICK_DELTA                 1210
#define SPN_HOLD_DELTA_EDIT             1211
#define SPN_HOLD_DELTA                  1212
#define SPN_MIN_EDIT                    1213
#define SPN_MIN                         1214
#define SPN_MAX_EDIT                    1215
#define SPN_MAX                         1216
#define EDIT_TOOLTIP                    1217
#define CMB_CURSOR                      1218
#define EDIT_COMMAND                    1220
#define DLG_DC                          1220
#define BTN_COMMAND                     1221
#define DLG_EDIT_DATAREF                1221
#define EDIT_COMMAND2                   1222
#define DLG_EDIT_CPMMAND                1222
#define DLG_EDIT_COMMAND                1222
#define BTN_COMMAND2                    1223
#define SPN_Z_EDIT                      1224
#define SPN_Y_EDIT                      1225
#define SPN_X_EDIT                      1226
#define SPN_X                           1227
#define SPN_Y                           1228
#define SPN_Z                           1229
#define SPN_HOLD_EDIT                   1230
#define SPN_HOLD                        1231
#define SPN_DOWN_EDIT                   1232
#define SPN_DOWN                        1233
#define SPN_V1_EDIT                     1234
#define SPN_V2_EDIT                     1235
#define SPN_V2                          1236
#define SPN_V1                          1237
#define LBL_NAME                        1238
#define CHK_AUTOEXPORT                  1239
#define LST_OBJECTS                     1240
#define BTN_SELECT_ALL                  1241
#define BTN_UNSELECT_ALL                1242
#define STC_XOBJ_EXPORT                 1243
#define BTN_UPDATE                      1244
#define STC_VALUE2                      1245
#define STC_VALUE1                      1246
#define CMB_SMOKE_TYPE                  1248
#define SPN_SMOKE_SIZE_EDIT             1249
#define SPN_SMOKE_SIZE                  1250
#define EDT_INFO                        1252
#define EDT_OBJECTS                     1255
#define SPN_LIGHTLEVEL_V1_LABEL         1256
#define SPN_LIGHTLEVEL_V2_LABEL         1257
#define SPN_POLYOFFSET_DIST_LABEL       1258
#define SPN_BLEND_LABEL                 1259
#define SPN_SHINY_LABEL                 1260
#define IDC_NAME_LIGHTNAMED             1261
#define IDC_LIST                        1262
#define IDC_COMBO_FILES                 1264
#define IDC_PATH                        1265
#define EDIT_SEARCH                     1266
#define IDC_PATH_TYPE                   1267
#define LBL_DESCRIPTION                 1268
#define LBL_VALUE_TYPE                  1269
#define LBL_VALUE_UNITS                 1270
#define LBL_KEY                         1271
#define CHK_WRITABLE                    1272

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1273
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
